tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "autojump"
brew "bat"
brew "fzf"
brew "gh"
brew "git", link: false
brew "jq"
brew "neovim"
brew "node"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
